import React from 'react'
import Sathyacounter from './Sathyacounter'

function Content(vaishu) {
  return (
    <>
    <div>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero recusandae iste cumque necessitatibus consectetur reiciendis autem beatae tempora perferendis sed laborum impedit id fuga commodi labore vel, quo magnam maiores ratione nisi, dolore debitis. Doloribus modi ducimus, ex accusantium accusamus et recusandae aut quas aspernatur placeat, impedit beatae adipisci culpa, unde eos vero. Aliquam alias excepturi, fugiat sint recusandae asperiores. Repellat fuga cupiditate reiciendis provident illo accusamus odit suscipit, iusto libero laborum, autem commodi. Ipsa perferendis ea iure delectus illum amet voluptatum quasi cupiditate, a, autem maxime recusandae quisquam temporibus. Quasi dolore, possimus omnis ipsam a voluptatem architecto iusto quia ducimus quae ipsa porro. Iure illo exercitationem obcaecati dignissimos voluptatum asperiores, officiis vitae nemo, libero ad tempore consequuntur facilis laborum molestiae sapiente perferendis, autem similique aliquid enim id ut quas! Accusantium asperiores repellendus doloremque fugiat, incidunt eligendi alias dolor sunt quasi laudantium architecto unde ad a aut ipsum id provident officiis et ipsam error amet quibusdam omnis. Molestias doloremque amet at ullam vel recusandae cumque veritatis dicta ad vero dignissimos, sint animi corporis modi necessitatibus in officia atque fuga fugiat fugit eveniet pariatur alias minus! Beatae aspernatur culpa, minima vitae doloribus vel iusto iste totam unde maiores, voluptatibus animi non.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero recusandae iste cumque necessitatibus consectetur reiciendis autem beatae tempora perferendis sed laborum impedit id fuga commodi labore vel, quo magnam maiores ratione nisi, dolore debitis. Doloribus modi ducimus, ex accusantium accusamus et recusandae aut quas aspernatur placeat, impedit beatae adipisci culpa, unde eos vero. Aliquam alias excepturi, fugiat sint recusandae asperiores. Repellat fuga cupiditate reiciendis provident illo accusamus odit suscipit, iusto libero laborum, autem commodi. Ipsa perferendis ea iure delectus illum amet voluptatum quasi cupiditate, a, autem maxime recusandae quisquam temporibus. Quasi dolore, possimus omnis ipsam a voluptatem architecto iusto quia ducimus quae ipsa porro. Iure illo exercitationem obcaecati dignissimos voluptatum asperiores, officiis vitae nemo, libero ad tempore consequuntur facilis laborum molestiae sapiente perferendis, autem similique aliquid enim id ut quas! Accusantium asperiores repellendus doloremque fugiat, incidunt eligendi alias dolor sunt quasi laudantium architecto unde ad a aut ipsum id provident officiis et ipsam error amet quibusdam omnis. Molestias doloremque amet at ullam vel recusandae cumque veritatis dicta ad vero dignissimos, sint animi corporis modi necessitatibus in officia atque fuga fugiat fugit eveniet pariatur alias minus! Beatae aspernatur culpa, minima vitae doloribus vel iusto iste totam unde maiores, voluptatibus animi non.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero recusandae iste cumque necessitatibus consectetur reiciendis autem beatae tempora perferendis sed laborum impedit id fuga commodi labore vel, quo magnam maiores ratione nisi, dolore debitis. Doloribus modi ducimus, ex accusantium accusamus et recusandae aut quas aspernatur placeat, impedit beatae adipisci culpa, unde eos vero. Aliquam alias excepturi, fugiat sint recusandae asperiores. Repellat fuga cupiditate reiciendis provident illo accusamus odit suscipit, iusto libero laborum, autem commodi. Ipsa perferendis ea iure delectus illum amet voluptatum quasi cupiditate, a, autem maxime recusandae quisquam temporibus. Quasi dolore, possimus omnis ipsam a voluptatem architecto iusto quia ducimus quae ipsa porro. Iure illo exercitationem obcaecati dignissimos voluptatum asperiores, officiis vitae nemo, libero ad tempore consequuntur facilis laborum molestiae sapiente perferendis, autem similique aliquid enim id ut quas! Accusantium asperiores repellendus doloremque fugiat, incidunt eligendi alias dolor sunt quasi laudantium architecto unde ad a aut ipsum id provident officiis et ipsam error amet quibusdam omnis. Molestias doloremque amet at ullam vel recusandae cumque veritatis dicta ad vero dignissimos, sint animi corporis modi necessitatibus in officia atque fuga fugiat fugit 

     
    </div>
    
    <Sathyacounter silent={vaishu.Counter} updatesilent={vaishu.updateFunction} count2={vaishu.Counter2} updatesCount2={vaishu.updateFunction2} count3={vaishu.Counter3} updatesCount3={vaishu.updateFunction3}/>
    </>
  )
}

export default Content
